// projet-frontend/src/app/components/login/login.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import { Router } from '@angular/router';



@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;

  constructor(private formBuilder: FormBuilder,private router: Router) {}

  onSignUpClick() {
    this.router.navigate(['/signup']); // Replace '/signup' with the desired URL path
  }


  ngOnInit(): void {
    this.loginForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required]
    });
  }

  onSubmit() {
    if (this.loginForm.invalid) {
      return;
    }

    const email = this.loginForm.value.email;
    const password = this.loginForm.value.password;

    // Perform login authentication with email and password
    // ...
  }
}


<body>
<form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="login-form">
  <div class="logo-image">
    <img src="assets/images/system_logo.png" alt="Logo" class="logo">
  </div>

  <div class="form-group">
    <input type="email" id="email" placeholder="Enter your email" formControlName="email" required >
  </div>
  <div class="form-group">
    <input type="password" id="password"  placeholder="Enter your password" formControlName="password" required >
    <button mat-icon-button matSuffix (click)="hide = !hide" [attr.aria-label]="'Hide password'" [attr.aria-pressed]="hide">
      <mat-icon>{{hide ? 'visibility_off' : 'visibility'}}</mat-icon>
    </button>
  </div>
  <button type="submit" [disabled]="loginForm.invalid" class="btn-login">Login</button>
  <div class="signUp">
    <strong>No Account?</strong> <a routerLink="/signup" (click)="onSignUpClick()">Sign up</a>
  </div>
</form>

</body>

// react-frontend/src/pages/LoginPage/components/LoginComponent/LoginComponent.js
import './LoginComponent.css';
import React, {useState} from "react";
import { FaEye, FaEyeSlash } from 'react-icons/fa';
import logo from "../../../../assets/images/logo.png";
import {Link} from "react-router-dom";
function LoginComponent(){
    const [showPassword, setShowPassword] = useState(false);
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const onSubmit = (e) => {
        e.preventDefault();
        // Add your login logic here
    };

    const togglePasswordVisibility = () => {
        setShowPassword(!showPassword);
    };

    return(
        <div className="container">
            <form className="login-form">
                    <img src={logo} alt="Logo" className="logo" />
                <div className="email-input">
                    <input
                        type="email"
                        id="email"
                        placeholder="Enter your email"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        required />
                    </div>

                <div className="password-input ">
                    <input
                        type={showPassword ? 'text' : 'password'}
                        id="password"
                        placeholder="Enter your password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        required
                        className="field" />
                    <span className="toggle-pass" onClick={togglePasswordVisibility}>
    {showPassword ? <FaEyeSlash /> : <FaEye />}
                    </span>
                </div>

                <div className="forgot-password">Forgot my password?</div>
                <br/>
                <Link to="/home">
                    <button type="submit" disabled={!email || !password} className="btn-login">Login</button>
                </Link>
                    <div className="signUp"><strong>No Account?</strong> <Link to="/signup">Signup</Link>
                    </div>
                </form>
        </div>
    );

}

export default LoginComponent;
